"""create jobs and segments tables

Revision ID: 43985df5ff20
Revises: 
Create Date: 2026-08-24 18:20:19.932312

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = '43985df5ff20'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Autogenerate doesn't emit enum creation/dropout — handle explicitly.
    # (Downgrade leaves the type behind; recreate idempotently.)
    op.execute("DROP TYPE IF EXISTS job_status")
    op.execute("""
        CREATE TYPE job_status AS ENUM
          ('PENDING','RUNNING','COMPLETED','FAILED','DEAD_LETTERED','CANCELLED');
    """)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_lang', sa.String(length=10), nullable=False),
    sa.Column('target_lang', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'DEAD_LETTERED', 'CANCELLED', name='job_status').with_variant(postgresql.ENUM('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'DEAD_LETTERED', 'CANCELLED', name='job_status', create_type=False), 'postgresql'), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_jobs_status_created', 'jobs', ['status', 'created_at'], unique=False)
    op.create_table('segments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('source_text', sa.String(), nullable=True),
    sa.Column('translated_text', sa.String(), nullable=True),
    sa.Column('audio_path', sa.String(), nullable=True),
    sa.Column('qc_score', sa.Float(), nullable=True),
    sa.Column('qc_passed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_segments_job_index', 'segments', ['job_id', 'index'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_segments_job_index', table_name='segments')
    op.drop_table('segments')
    op.drop_index('ix_jobs_status_created', table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
