"""add assets and usage_records

Revision ID: 6581c84b56af
Revises: a52d431d1c36
Create Date: 2026-08-24 19:13:08.480536

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = '6581c84b56af'
down_revision: str | None = 'a52d431d1c36'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('checksum_sha256', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_assets_job_role', 'assets', ['job_id', 'role'], unique=False)
    op.create_table('usage_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('api_key_id', sa.String(length=64), nullable=True),
    sa.Column('engine', sa.String(length=32), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_usage_apikey_created', 'usage_records', ['api_key_id', 'created_at'], unique=False)
    op.create_index('ix_usage_job', 'usage_records', ['job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_usage_job', table_name='usage_records')
    op.drop_index('ix_usage_apikey_created', table_name='usage_records')
    op.drop_table('usage_records')
    op.drop_index('ix_assets_job_role', table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
