"""add stage_completions idempotency ledger

Revision ID: a52d431d1c36
Revises: 43985df5ff20
Create Date: 2026-08-24 18:58:45.535870

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = 'a52d431d1c36'
down_revision: str | None = '43985df5ff20'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stage_completions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.String(length=32), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_stage_completions_job_stage', 'stage_completions', ['job_id', 'stage'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_stage_completions_job_stage', table_name='stage_completions')
    op.drop_table('stage_completions')
    # ### end Alembic commands ###
